INSERT INTO 
ingredients (name)
VALUES 
('Bread'),
('Cheese'),
('Ham'),
('Mayo'),
('Mustard'),
('Beef Patty'),
('Lettuce'),
('Bacon'),
('Tomato'),
('Chicken'),
('Steak'),
('Tortilla'),
('Bean'),
('Hamburger Buns'),
('Alcohol'),
('Caffeine'),
('Celery'),
('Egg'),
('Gluten'),
('Peanut'),
('Dairy'),
('Sesame'),
('Soy'),
('Tree Nut'), 
('Wheat'),
('Apple'),
('Banana'),
('Broccoli'),
('Kale'),
('Pizza'),
('Butter'),
('Yeast'),
('Ingredient 1'),
('Ingredient 2'),
('Ingredient 3'),
('Ingredient 4'),
('Ingredient 5'),
('Ingredient 6'),
('Ingredient 7'),
('Ingredient 8'),
('Ingredient 9'),
('Ingredient 10'),
('Ingredient 11'),
('Ingredient 12'),
('Ingredient 13'),
('Ingredient 14'),
('Ingredient 15'),
('Ingredient 16'),
('Ingredient 17'),
('Ingredient 18'),
('Ingredient 19'),
('Ingredient 20');